version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
      - "50051:50051"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - my_network

  traffic-generator:
    build: .
    container_name: traffic-generator
    command: python /app/consultas.py
    depends_on:
      - app
    networks:
      - my_network

  redis1:
    image: bitnami/redis:latest
    container_name: redis1
    ports:
      - "6379:6379"
    environment:
      - REDIS_MAXMEMORY=1mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my_network


networks:
  my_network:
    driver: bridge

