# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dns.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'dns.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdns.proto\" \n\x0eResolveRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\"\x1d\n\x0fResolveResponse\x12\n\n\x02ip\x18\x01 \x01(\t2=\n\x0b\x44NSResolver\x12.\n\x07Resolve\x12\x0f.ResolveRequest\x1a\x10.ResolveResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dns_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOLVEREQUEST']._serialized_start=13
  _globals['_RESOLVEREQUEST']._serialized_end=45
  _globals['_RESOLVERESPONSE']._serialized_start=47
  _globals['_RESOLVERESPONSE']._serialized_end=76
  _globals['_DNSRESOLVER']._serialized_start=78
  _globals['_DNSRESOLVER']._serialized_end=139
# @@protoc_insertion_point(module_scope)
