version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
      - "50051:50051"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - my_network

  traffic-generator:
    build: .
    container_name: traffic-generator
    command: python /app/consultas.py
    depends_on:
      - app
    networks:
      - my_network

  redis1:
    image: bitnami/redis:latest
    container_name: redis1
    ports:
      - "6379:6379"
    environment:
      - REDIS_MAXMEMORY=1mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my_network

  redis2:
    image: bitnami/redis:latest
    container_name: redis2
    ports:
      - "6380:6379"
    environment:
      - REDIS_MAXMEMORY=1mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my_network

  redis3:
    image: bitnami/redis:latest
    container_name: redis3
    ports:
      - "6381:6379"
    environment:
      - REDIS_MAXMEMORY=1mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lfu
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my_network

  redis4:
    image: bitnami/redis:latest
    container_name: redis4
    ports:
      - "6382:6379"
    environment:
      - REDIS_MAXMEMORY=1mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lfu
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my_network
   redis5:
    image: bitnami/redis:latest
    container_name: redis1
    ports:
      - "6383:6379"
    environment:
      - REDIS_MAXMEMORY=1mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my_network

  redis6:
    image: bitnami/redis:latest
    container_name: redis2
    ports:
      - "6384:6379"
    environment:
      - REDIS_MAXMEMORY=1mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my_network

  redis7:
    image: bitnami/redis:latest
    container_name: redis3
    ports:
      - "6385:6379"
    environment:
      - REDIS_MAXMEMORY=1mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lfu
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my_network

  redis8:
    image: bitnami/redis:latest
    container_name: redis4
    ports:
      - "6386:6379"
    environment:
      - REDIS_MAXMEMORY=1mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lfu
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

